import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { generateSystem, generatePlanet, systemForId } from './system';
import { generateStars } from './stars';
import { Rng, hash2, seedFromString } from '../random.js';
import { canonicalJson } from '../canonical.js';
import { RESOURCE_TYPES, SHIP_CLASS_IDS } from './config.js';
import fixture from './__fixtures__/system-dev-seed-star0.json';

const DEV_SEED = fixture.seed;
const STAR0_ID = fixture.starId;
const SEEDS = ['drift-dev-seed-001', 'galaxy-alpha', 'Ω-unicode-∞', ''];

/** Structural invariants every generated system must satisfy. */
function assertSystemInvariants(system: ReturnType<typeof generateSystem>) {
  expect(system.systemId).toMatch(/^[0-9a-f]{16}$/);
  expect(system.name).toBe(`${system.star.name} system`);
  expect(system.planets.length).toBeGreaterThanOrEqual(2);
  expect(system.planets.length).toBeLessThanOrEqual(6);

  const seenIds = new Set<string>();
  const seenNames = new Set<string>();
  const rosterClasses = new Set<string>(SHIP_CLASS_IDS);
  for (const p of system.planets) {
    expect(p.id).toMatch(/^[0-9a-f]{16}$/);
    expect(seenIds.has(p.id)).toBe(false);
    seenIds.add(p.id);
    expect(seenNames.has(p.name)).toBe(false);
    seenNames.add(p.name);

    // Radius bounds by class.
    if (p.class === 'gas') {
      expect(p.radiusKm).toBeGreaterThanOrEqual(20000);
      expect(p.radiusKm).toBeLessThan(60000);
    } else {
      expect(p.radiusKm).toBeGreaterThanOrEqual(2000);
      expect(p.radiusKm).toBeLessThan(8000);
    }

    // Gas giants are never landable; landable planets have at least one dock.
    if (p.class === 'gas') {
      expect(p.landable).toBe(false);
      expect(p.dockCount).toBe(0);
    } else if (p.landable) {
      expect(p.dockCount).toBeGreaterThanOrEqual(1);
      expect(p.dockCount).toBeLessThanOrEqual(3);
    } else {
      expect(p.dockCount).toBe(0);
    }

    // Resource deposit fields: 1..3, unique, from the known set.
    expect(p.resourceTypes.length).toBeGreaterThanOrEqual(1);
    expect(p.resourceTypes.length).toBeLessThanOrEqual(3);
    expect(new Set(p.resourceTypes).size).toBe(p.resourceTypes.length);
    for (const t of p.resourceTypes) expect(RESOURCE_TYPES).toContain(t);

    // AI roster: count 2..5, classes from the 3 TASK-19 ids, one per ship.
    expect(p.aiRoster.count).toBeGreaterThanOrEqual(2);
    expect(p.aiRoster.count).toBeLessThanOrEqual(5);
    expect(p.aiRoster.classes.length).toBe(p.aiRoster.count);
    for (const c of p.aiRoster.classes) expect(rosterClasses.has(c)).toBe(true);
  }
}

describe('generateSystem', () => {
  it('golden snapshot: deep-equals the committed fixture for star #0 of the dev seed', () => {
    const system = generateSystem(DEV_SEED, STAR0_ID);
    expect(system).toEqual(fixture.system);
    const checksum = createHash('sha256').update(canonicalJson(system)).digest('hex');
    expect(checksum).toBe(fixture.checksum);
  });

  it('is deterministic across two calls', () => {
    expect(generateSystem(DEV_SEED, STAR0_ID)).toEqual(generateSystem(DEV_SEED, STAR0_ID));
  });

  it('is identical when each planet is generated by its own independent Rng instance', () => {
    const system = generateSystem(DEV_SEED, STAR0_ID);
    for (let j = 0; j < system.planets.length; j++) {
      // Fresh, independent Rng per planet (via generatePlanet's own sub-seed).
      expect(generatePlanet(DEV_SEED, STAR0_ID, j)).toEqual(system.planets[j]);
    }
  });

  it('derives the same draws from two independent Rng instances seeded identically', () => {
    const subSeed = hash2(seedFromString(DEV_SEED), seedFromString(STAR0_ID));
    const a = new Rng(subSeed);
    const b = new Rng(subSeed);
    for (let i = 0; i < 32; i++) expect(a.nextU32()).toBe(b.nextU32());
  });

  it('diverges for different star ids and different seeds', () => {
    const base = generateSystem(DEV_SEED, STAR0_ID);
    expect(generateSystem(DEV_SEED, 'ffffffffffffffff')).not.toEqual(base);
    expect(generateSystem('other-seed', STAR0_ID)).not.toEqual(base);
  });

  it('matches the system sub-seed formula: systemId = hex(hash2(masterSeed, starIdSeed))', () => {
    const expected = hash2(seedFromString(DEV_SEED), seedFromString(STAR0_ID))
      .toString(16)
      .padStart(16, '0');
    expect(generateSystem(DEV_SEED, STAR0_ID).systemId).toBe(expected);
  });
});

describe('system invariants over 200 generated systems (dev seed)', () => {
  const stars = generateStars(DEV_SEED);
  const systems = stars.map((s) => generateSystem(DEV_SEED, s.id));

  it('generates 2..6 planets, with valid fields, in every system', () => {
    expect(systems.length).toBe(200);
    for (const s of systems) assertSystemInvariants(s);
  });

  it('has unique system ids across the 200 systems', () => {
    const ids = new Set(systems.map((s) => s.systemId));
    expect(ids.size).toBe(200);
  });

  it('has at least one landable planet with atmosphere in >80% of systems', () => {
    const good = systems.filter((s) => s.planets.some((p) => p.landable && p.hasAtmosphere)).length;
    expect(good / systems.length).toBeGreaterThan(0.8);
  });

  it('never generates a landable gas giant', () => {
    for (const s of systems) {
      for (const p of s.planets) {
        if (p.class === 'gas') expect(p.landable).toBe(false);
      }
    }
  });
});

for (const seed of SEEDS.filter((s) => s !== DEV_SEED)) {
  describe(`invariants for other seeds: "${seed}"`, () => {
    const systems = generateStars(seed, 30).map((s) => generateSystem(seed, s.id));

    it('satisfies every structural invariant', () => {
      for (const s of systems) assertSystemInvariants(s);
    });

    it('is deterministic for every system', () => {
      for (const star of generateStars(seed, 30)) {
        expect(generateSystem(seed, star.id)).toEqual(generateSystem(seed, star.id));
      }
    });
  });
}

describe('systemForId (TASK-8: seed lookup for warp targets)', () => {
  const stars = generateStars(DEV_SEED);

  it('finds a system by id and matches the direct derivation', () => {
    const want = generateSystem(DEV_SEED, stars[3].id);
    expect(systemForId(DEV_SEED, want.systemId)).toEqual(want);
  });

  it('returns undefined for an unknown id', () => {
    expect(systemForId(DEV_SEED, 'ffffffffffffffff')).toBeUndefined();
  });

  it('memoizes per (seed, id): repeated lookups return the same object', () => {
    const want = generateSystem(DEV_SEED, stars[5].id);
    expect(systemForId(DEV_SEED, want.systemId)).toBe(systemForId(DEV_SEED, want.systemId));
    // A different seed never shares a cached entry.
    expect(systemForId('other-seed', want.systemId)).toBeUndefined();
  });
});
